### ISSUE TITLE
Parsing utmz from a string instead of reading a cookie

### ISSUE THREAD

**Issue by iwazaru** [jamesflight/Google-Analytics-Cookie-Parser-PHP#2]
Hi,

I'm a working on an ecommerce application. Whenever a new order is created by a customer, it stores the value of the `utmz` cookie in a field of the database along with the order. I'd like to use your library to parse that field and extract the source, campaign and medium parameters from the raw string.

As I understand it, the library directly reads from the cookies sent with the request. Would it be complicated to modify it so could also parse a string that was previously saved? Something like:

    $utmz = GACookie::parseString('utmz', '177910838.1481550491.52.15.utmcsr=newsletter|utmccn=campaign-2016|utmcmd=email');

Thanks,

Clément

**Comment by iwazaru** [comment]
Are you still maintaining this library? Would you accept a pull request to implement this feature?

**Comment by jamesflight** [comment]
If this would be useful to you, I'd be happy to accept a PR
